### ISSUE TITLE
Invalid host for Bitbucket / Gitlab

### ISSUE THREAD

**Issue by pomek** [jonschlinkert/parse-github-url#10]
Hi,

For the code below, `parseGithubUrl` returns an invalid `host`:

```js
const parseGithubUrl = require( 'parse-github-url' );
const repositoryInfo = parseGithubUrl( 'git@gitlab.com:assemble/verb.git#v1.2.3' );
console.log( repositoryInfo );
Url {
	protocol: null,
	slashes: null,
	auth: null,
	host: 'github.com',
	port: null,
	hostname: null,
	hash: '#v1.2.3',
	search: null,
	query: null,
	pathname: 'git@gitlab.com:assemble/verb.git',
	path: 'git@gitlab.com:assemble/verb.git',
	href: 'git@gitlab.com:assemble/verb.git#v1.2.3',
	filepath: null,
	owner: 'assemble',
	name: 'verb',
	repo: 'assemble/verb',
	branch: 'v1.2.3',
	repository: 'assemble/verb' 
}
```

**Comment by tunnckoCore** [comment]
i believe it's because the`obj.repo || 'github.com' ` line (search for it), prs welcome.  :)

**Comment by doowb** [comment]
It looks like if you don't provide a protocol (e.g. `http://`, `https://`, or `git://` the `url` library doesn't return a `host` property so this library defaults to `github.com` for the host.

Also, you have a `:` between the host and the path, shouldn't that be a `/`?
