### ISSUE TITLE
Feature request: a path

### ISSUE THREAD

**Issue by finom** [jonschlinkert/parse-github-url#6]
I'd be happy to have possibility to get a path somehow. Eg extract `path/to/file.json` from such URL `https://github.com/owner/repo/blob/branch/path/to/file.json`

Thank you

**Comment by ljharb** [comment]
`require('parse-github-url')('https://github.com/owner/repo/blob/branch/path/to/file.json').filepath === 'path/to/file.json'`, so i think this has been implemented since this issue was filed.
