### ISSUE TITLE
Preserve leading hypens

### ISSUE THREAD

**Issue by pyrotechnick** [jonschlinkert/parse-github-url#8]
Leading hypens are unnecessarily stripped

e.g. https://github.com/binjospookie/--shots is parsed as 

```js
{
  host: 'github.com',
  owner: 'binjospookie',
  name: 'shots',
  repo: 'binjospookie/shots',
  repository: 'binjospookie/shots',
  branch: 'master'
}
```

**Comment by jonschlinkert** [comment]
sorry for the late reply, I was out with a cold at the time and I'm just now getting caught up. definitely a bug.  thanks for reporting
